apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-1-ebs-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
