apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-1
  namespace: dev
  labels:
    app: wordpress-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: wordpress-1
        tier: frontend
        version: ${BUILD_NUMBER}
    spec:
      containers:
      - image: wordpress
        name: wordpress-1
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        ports:
        - containerPort: 80
          name: wordpress-1
        readinessProbe:
#          tcpSocket:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
#          tcpSocket:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 2
          failureThreshold: 3
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-1-ebs-claim
