kind: Service
apiVersion: v1
metadata:
  name: nginx-wordpress
  labels:
    app: nginx-wordpress
spec:
  type: NodePort
  selector:
    app: nginx-wordpress
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80 
