apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "wordpress-ingress"
  namespace: "dev"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-0af2a5b8714ccb381, sg-02f080e5efe422218
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:294387193228:certificate/ed86172e-ffda-46e0-881e-b2bdea07501d
  labels:
    app: wordpress-ingress
spec:
  rules:
  #  - host: wordpress.yphanikumar.xyz
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: nginx-wordpress
              servicePort: 80
