apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-2
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mysql-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-2
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-1
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user		
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-2-ebs-claim
