apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-2-ebs-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 3Gi
